global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'edgex'
    static_configs:
      - targets: ['edgex-exporter:9410']
        labels:
          group: 'edgex'

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.17.0.1:9100']
